{
  "Header": {
    "Original": "CVE-2024-6232 (There is a MEDIUM severity vulnerability affecting CPython.      Regul ...)",
    "ID": "CVE-2024-6232",
    "Description": "(There is a MEDIUM severity vulnerability affecting CPython.      Regul ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3980-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3980-1"
      ]
    },
    {
      "Original": "- python3.13 3.13.0~rc2-1",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "fixed",
      "Version": "3.13.0~rc2-1"
    },
    {
      "Original": "- python3.12 3.12.6-1",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "fixed",
      "Version": "3.12.6-1"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 3.11.2-6+deb12u4",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "fixed",
      "Version": "3.11.2-6+deb12u4"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python2.7 \u003cignored\u003e (Unsupported in Bullseye, only included to build a few applications)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python2.7",
      "Kind": "ignored",
      "Description": "Unsupported in Bullseye, only included to build a few applications"
    },
    {
      "Original": "- pypy3 7.3.18+dfsg-1",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.18+dfsg-1"
    },
    {
      "Original": "[bookworm] - pypy3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pypy3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/121285",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/121285"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/121286",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/121286"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/ed3a49ea734ada357ff4442996fd4ae71d253373 (v3.13.0rc2)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/ed3a49ea734ada357ff4442996fd4ae71d253373 (v3.13.0rc2)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06 (v3.12.6)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06 (v3.12.6)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/d449caf8a179e3b954268b3a88eb9170be3c8fbf (v3.11.10)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/d449caf8a179e3b954268b3a88eb9170be3c8fbf (v3.11.10)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/743acbe872485dc18df4d8ab2dc7895187f062c4 (v3.10.15)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/743acbe872485dc18df4d8ab2dc7895187f062c4 (v3.10.15)"
    }
  ]
}