{
  "Header": {
    "Original": "CVE-2025-55559 (An issue was discovered TensorFlow v2.18.0. A Denial of Service (DoS)  ...)",
    "ID": "CVE-2025-55559",
    "Description": "(An issue was discovered TensorFlow v2.18.0. A Denial of Service (DoS)  ...)"
  },
  "Annotations": [
    {
      "Original": "- tensorflow \u003cunfixed\u003e (unimportant)",
      "Type": "package",
      "Package": "tensorflow",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/tensorflow/tensorflow/issues/84205",
      "Type": "NOTE",
      "Description": "https://github.com/tensorflow/tensorflow/issues/84205"
    },
    {
      "Original": "NOTE: Negligible security impact",
      "Type": "NOTE",
      "Description": "Negligible security impact"
    }
  ]
}