{
  "Header": {
    "Original": "CVE-2025-62708 (pypdf is a free and open-source pure-python PDF library. Prior to vers ...)",
    "ID": "CVE-2025-62708",
    "Description": "(pypdf is a free and open-source pure-python PDF library. Prior to vers ...)"
  },
  "Annotations": [
    {
      "Original": "- pypdf \u003cunfixed\u003e (bug #1118756)",
      "Type": "package",
      "Package": "pypdf",
      "Kind": "unfixed",
      "BugNo": 1118756
    },
    {
      "Original": "[bookworm] - pypdf \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pypdf",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/pypdf/security/advisories/GHSA-jfx9-29x2-rv3j",
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/pypdf/security/advisories/GHSA-jfx9-29x2-rv3j"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/pypdf/pull/3502",
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/pypdf/pull/3502"
    },
    {
      "Original": "NOTE: Introduced with: https://github.com/py-pdf/pypdf/commit/e825ac07ea89c78962646245e348b934d48f9629 (5.1.0)",
      "Type": "NOTE",
      "Description": "Introduced with: https://github.com/py-pdf/pypdf/commit/e825ac07ea89c78962646245e348b934d48f9629 (5.1.0)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/py-pdf/pypdf/commit/e51d07807ffcdaf18077b9486dadb3dc05b368da (6.1.3)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/py-pdf/pypdf/commit/e51d07807ffcdaf18077b9486dadb3dc05b368da (6.1.3)"
    }
  ]
}