{
  "Header": {
    "Original": "CVE-2025-46150 (In PyTorch before 2.7.0, when torch.compile is used, FractionalMaxPool ...)",
    "ID": "CVE-2025-46150",
    "Description": "(In PyTorch before 2.7.0, when torch.compile is used, FractionalMaxPool ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/141538",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/141538"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/pull/144395",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/pull/144395"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/pytorch/pytorch/commit/ccc2878c978258ec88f7ec591305ba5b13e06579 (v2.7.0-rc1)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/pytorch/pytorch/commit/ccc2878c978258ec88f7ec591305ba5b13e06579 (v2.7.0-rc1)"
    }
  ]
}