{
  "Header": {
    "Original": "CVE-2025-38494 (In the Linux kernel, the following vulnerability has been resolved:  H ...)",
    "ID": "CVE-2025-38494",
    "Description": "(In the Linux kernel, the following vulnerability has been resolved:  H ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5975-1 DSA-5973-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5975-1",
        "DSA-5973-1"
      ]
    },
    {
      "Original": "- linux 6.16.3-1",
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "6.16.3-1"
    },
    {
      "Original": "NOTE: https://git.kernel.org/linus/c2ca42f190b6714d6c481dfd3d9b62ea091c946b (6.16-rc7)",
      "Type": "NOTE",
      "Description": "https://git.kernel.org/linus/c2ca42f190b6714d6c481dfd3d9b62ea091c946b (6.16-rc7)"
    },
    {
      "Original": "NOTE: https://github.com/xairy/kernel-exploits/tree/master/CVE-2025-38494",
      "Type": "NOTE",
      "Description": "https://github.com/xairy/kernel-exploits/tree/master/CVE-2025-38494"
    }
  ]
}