{
  "Header": {
    "Original": "CVE-2025-55552 (pytorch v2.8.0 was discovered to display unexpected behavior when the  ...)",
    "ID": "CVE-2025-55552",
    "Description": "(pytorch v2.8.0 was discovered to display unexpected behavior when the  ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e (bug #1116536)",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed",
      "BugNo": 1116536
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/147847",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/147847"
    }
  ]
}