{
  "Header": {
    "Original": "CVE-2025-50817 (A vulnerability in the Python-Future 1.0.0 module allows for arbitrary ...)",
    "ID": "CVE-2025-50817",
    "Description": "(A vulnerability in the Python-Future 1.0.0 module allows for arbitrary ...)"
  },
  "Annotations": [
    {
      "Original": "NOTE: Bogus Python-Future issue",
      "Type": "NOTE",
      "Description": "Bogus Python-Future issue"
    },
    {
      "Original": "NOTE: https://github.com/PythonCharmers/python-future/issues/268",
      "Type": "NOTE",
      "Description": "https://github.com/PythonCharmers/python-future/issues/268"
    },
    {
      "Original": "NOTE: Project is EOL/unmaintained; no upstream fix is likely.",
      "Type": "NOTE",
      "Description": "Project is EOL/unmaintained; no upstream fix is likely."
    },
    {
      "Original": "NOTE: CVE may be rejected. https://github.com/PythonCharmers/python-future/issues/650#issuecomment-3252409616",
      "Type": "NOTE",
      "Description": "CVE may be rejected. https://github.com/PythonCharmers/python-future/issues/650#issuecomment-3252409616"
    }
  ]
}