{
  "Header": {
    "Original": "CVE-2025-62707 (pypdf is a free and open-source pure-python PDF library. Prior to vers ...)",
    "ID": "CVE-2025-62707",
    "Description": "(pypdf is a free and open-source pure-python PDF library. Prior to vers ...)"
  },
  "Annotations": [
    {
      "Original": "- pypdf \u003cunfixed\u003e (bug #1118755)",
      "Type": "package",
      "Package": "pypdf",
      "Kind": "unfixed",
      "BugNo": 1118755
    },
    {
      "Original": "[bookworm] - pypdf \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pypdf",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/pypdf/security/advisories/GHSA-vr63-x8vc-m265",
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/pypdf/security/advisories/GHSA-vr63-x8vc-m265"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/pypdf/pull/3501",
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/pypdf/pull/3501"
    },
    {
      "Original": "NOTE: Introduced with: https://github.com/py-pdf/pypdf/commit/23a81baad19e14ecaaa1949e52edd531b1c49efd (4.3.0)",
      "Type": "NOTE",
      "Description": "Introduced with: https://github.com/py-pdf/pypdf/commit/23a81baad19e14ecaaa1949e52edd531b1c49efd (4.3.0)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/py-pdf/pypdf/commit/f2864d6dd9bac7cecd3f4f54308b25ebbfa178f8 (6.1.3)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/py-pdf/pypdf/commit/f2864d6dd9bac7cecd3f4f54308b25ebbfa178f8 (6.1.3)"
    }
  ]
}